### ISSUE TITLE
Feature:  Support 16 KB page sizes

### ISSUE THREAD

**Issue by cmveas** [scottyab/rootbeer#241]
**Describe the bug/feature request/question**
We need a library that is aligned for 16KB memory pages as described here

https://developer.android.com/guide/practices/page-sizes

Do you think you might have an updated version with this kind of support?

**Comment by bhm** [comment]
Version 0.1.1 with 16kb was released in Sept 2024. 

https://github.com/scottyab/rootbeer/releases/tag/0.1.1

**Comment by cmveas** [comment]
In my report I still see 

/var/folders/95/7vdyp6cx38g4481n1t40zj8h0000gn/T/app-prod-debug_out_XXXXX.AS3CypP3ir/lib/x86/libtoolChecker.so: \e[31mUNALIGNED\e[0m (2**12)

Will this be fixed when 

https://github.com/scottyab/rootbeer/pull/244

is merged? will there be another version released?

**Comment by ABINAYASEL** [comment]
Hi, Same here. I have upgraded RootBeer to 0.1.1
But still found it is UNALIGNED

/var/folders/97/rrwwqgc138s466tqfbsbr3c80000gn/T/app-debug_aligned_out_XXXXX.lKQRG43oGO/lib/armeabi-v7a/libtoolChecker.so: \e[31mUNALIGNED\e[0m (2**12)

**Comment by corepuncher** [comment]
Update: Fixed it using 0.1.1.

**Comment by liamjones** [comment]
@corepuncher It's already done. See https://github.com/scottyab/rootbeer/issues/241#issuecomment-2604281957

People complaining about `x86` and `armeabi-v7a` libraries being unaligned haven't [read the docs](https://developer.android.com/guide/practices/page-sizes#alignment-use-script) and/or [the output from `check_elf_alignment.sh`](https://cs.android.com/android/platform/superproject/main/+/main:system/extras/tools/check_elf_alignment.sh;l=109):

> If any arm64-v8a or x86_64 shared libraries are UNALIGNED, you'll need to [update the packaging for those libraries](https://developer.android.com/guide/practices/page-sizes#update-packaging), then [recompile your app](https://developer.android.com/guide/practices/page-sizes#compile-16-kb-alignment)...

> only arm64-v8a/x86_64 libs need to be aligned

**Comment by cmveas** [comment]
@liamjones thanks for pointing out the mistake. I can confirm this is the case. 
Thanks for the support

**Comment by 0x0BB9** [comment]
> [@corepuncher](https://github.com/corepuncher) It's already done. See [#241 (comment)](https://github.com/scottyab/rootbeer/issues/241#issuecomment-2604281957)
> 
> People complaining about `x86` and `armeabi-v7a` libraries being unaligned haven't [read the docs](https://developer.android.com/guide/practices/page-sizes#alignment-use-script) and/or [the output from `check_elf_alignment.sh`](https://cs.android.com/android/platform/superproject/main/+/main:system/extras/tools/check_elf_alignment.sh;l=109):
> 
> > If any arm64-v8a or x86_64 shared libraries are UNALIGNED, you'll need to [update the packaging for those libraries](https://developer.android.com/guide/practices/page-sizes#update-packaging), then [recompile your app](https://developer.android.com/guide/practices/page-sizes#compile-16-kb-alignment)...
> 
> > only arm64-v8a/x86_64 libs need to be aligned

The problem is that even when I submit builds that include x86 and armeabi‑v7a libraries to Google Play, it still warns that we don’t meet the 16 KB page‑size requirement. Should I ignore the warning, or filter out x86 and armeabi‑v7a?

**Comment by liamjones** [comment]
@0x0BB9 Interesting, I've not got to submission yet on our apps. Are you submitting AABs or APKs? If it's APKs, are they split by ABI? If it was a universal APK, or, if it were split APKs and your 64-bit APKs were ending up with 32-bit libraries inside them somehow I can see how it'd probably still complain.

It might be worth querying with Google's dev support?

**Comment by 0x0BB9** [comment]
> [@0x0BB9](https://github.com/0x0BB9) Interesting, I've not got to submission yet on our apps. Are you submitting AABs or APKs? If it's APKs, are they split by ABI? If it was a universal APK, or, if it were split APKs and your 64-bit APKs were ending up with 32-bit libraries inside them somehow I can see how it'd probably still complain.
> 
> It might be worth querying with Google's dev support?

@liamjones   AABs, not APKs.

**Comment by K-K-Chong** [comment]
Any updates on this issue? i am facing this issue too.

**Comment by dyazincahya** [comment]
up

**Comment by pawarprasad37** [comment]
Any updates on this issue? i am facing this issue too.

**Comment by K-K-Chong** [comment]
Hi all, is anyone able to solve the issue? Mind to share the solution. Thanks 😊

**Comment by 0x0BB9** [comment]
Update:  fix it by adding the following configuration in build.gradle
`packagingOptions { jniLibs {useLegacyPackaging true}}`
or upgrade the Gradle version to 8.5 or above.

**Comment by K-K-Chong** [comment]
> Update: fix it by adding the following configuration in build.gradle `packagingOptions { jniLibs {useLegacyPackaging true}}` or upgrade the Gradle version to 8.5 or above.

the configuration above is to disable the apk to support 16kb? Please correct if I'm wrong. If yes, will it be rejected by google playstore?

**Comment by ice-psantos** [comment]
There was a problem in the Android Studio, that make the "Analyze APK" give the 16 KB warning. 
In the new version(Narwhal 3 Feature Drop | 2025.1.3) this issue is solved.
The issue: https://issuetracker.google.com/issues/432782053

**Comment by maavalos** [comment]
The problem  with the library isn't fixed, the deadline imposed by Play Store is near.

This is the warning from PlayStore for our app:

<img width="384" height="165" alt="Image" src="https://github.com/user-attachments/assets/492960be-8585-46f8-848e-d3732fe98172" />

The **librealmc.so** is related to rootbeer:

<img width="847" height="127" alt="Image" src="https://github.com/user-attachments/assets/bfe2a3cf-fc7f-42d1-b2af-a9ec12e2b865" />

**Comment by liamjones** [comment]
> The librealmc.so is related to rootbeer

@maavalos I'm not sure why you think that, rootbeer only produces a `libtoolChecker.so`: https://github.com/scottyab/rootbeer/blob/eff976a9eec1706957b2fa594672105fa9c3fa1e/rootbeerlib/src/main/cpp/CMakeLists.txt#L12

From a quick web search it looks like it's from realm-kotlin? https://github.com/realm/realm-kotlin/issues/1202

Over there, that was fixed and released in realm-kotlin 2.3.0: https://github.com/realm/realm-kotlin/pull/1834

**Comment by fanistheolog** [comment]
Hey guys i added rootbeer as a module in my app and did the following changes and it seems to work for me, if anyone want's to give it a shot as well
in the file `CMakeLists.txt`

```
if(ANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wl,-z,max-page-size=16384")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wl,-z,max-page-size=16384")
endif()
```

in the file `RootBeerTest.java`

from

```
import static org.mockito.Matchers.anyInt;
import static org.mockito.Matchers.anyString;
```

changed it to

```
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyString; 
```

if anyone gives it a shot and it works for him as well let me know so i can open a pull request and maybe get approved!

**Comment by airinterface** [comment]
I'm monitoring this conversation. Waiting for this to be resolved, signed and pushed to repository. 
Strange thing though, if I build  non release build, with my local Android Studio ( Build #AI-252.25557.131.2521.14432022, built on November 13, 2025 ) 
16 KB alignment for libtool-cheker.so says it's aligned.

**Comment by liamjones** [comment]
If you're using rootbeer 0.1.1 you should be fine, if you're not something else is going on with your setup. We're on 0.1.1 with releases in the store that are 16KB page size compatible.

**Comment by namitasabatphilips** [comment]
Any update on fixing the libtoolChecker.so to be 16kb aligned?

@gobetti, do you have any plan to release the fix in near future?

**Comment by jpgpuyo** [comment]
I confirm that 0.1.1 version is not supporting 16Kb size. It is still detecting libtool-checker.so (even with latest android studio).

**Comment by liamjones** [comment]
@namitasabatphilips @jpgpuyo 0.1.1 is fine, we literally have apps on the Play Store right now using it. At this point, they wouldn't have been approved by Google if they didn't meet the requirement.

Make sure you're not misunderstanding any results displayed by the Google alignment checking script, see https://github.com/scottyab/rootbeer/issues/241#issuecomment-3072296774

**Comment by jpgpuyo** [comment]
@liamjones Android Studio is still detecting this issue. Maybe there is a bug in Android Studio...

**Comment by liamjones** [comment]
@jpgpuyo possibly? You'd hope not for a company of Google's size.

You could try the shell script in the comment I linked above as an alternative and see if any of the 64-bit binaries are still saying they're unaligned.

Another way you could check is simply do an upload to Play Console - the store will complain if the alignment is wrong for 64-bit binaries or you'll see confirmation if it's good in the app bundle details page:

<img width="942" height="96" alt="Image" src="https://github.com/user-attachments/assets/7662921b-3ce9-4849-835f-e2de33958833" />

**Comment by namitasabatphilips** [comment]
@liamjones i am still getting these 2 UNALIGNED after running the google script. Could you help me understand if i am doing something wrong. Thanks

/lib/x86/libtoolChecker.so: \e[31mUNALIGNED\e[0m (2**12)
/lib/armeabi-v7a/libtoolChecker.so: \e[31mUNALIGNED\e[0m (2**12)

**Comment by NiallScott** [comment]
The requirement is that **64-bit** libraries must be 16KB page aligned - those are the libraries which live in the `arm64-v8a` and `x86_64` directories. `x86` and `armeabi-v7a` are 32-bit processor architectures and are thus not included in the requirement.

So for anybody coming to this issue and complaining that the library does not meet the 16KB alignment requirement, please please please check at what specific shared library file (`.so`) it is failing on and if it lives in the `x86` or `armeabi-v7a` directory, it is not an issue for you.

**Comment by gobetti** [comment]
I agree @NiallScott , the problem is that Google's tool reports it as non compliant nonetheless. Other than begging people to read through, alternatively we could release #244 (unless it has issues) which will silence this forever
