### ISSUE TITLE
UnsatisfiedLinkError on Samsung Galaxy s5 Neo (s5neolte) Android 6.0.1

### ISSUE THREAD

**Issue by antoninovitale** [scottyab/rootbeer#58]
java.lang.UnsatisfiedLinkError: 
  at com.scottyab.rootbeer.RootBeerNative.setLogDebugMessages (Native Method)
  at com.scottyab.rootbeer.b.i (SourceFile:373)
  at com.scottyab.rootbeer.b.a (SourceFile:45)

**Comment by zarnos** [comment]
Hi!
I have the same issue, one of our customers run into this on LeMobile LEX720:
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for int com.scottyab.rootbeer.RootBeerNative.setLogDebugMessages(boolean) (tried Java_com_scottyab_rootbeer_RootBeerNative_setLogDebugMessages and Java_com_scottyab_rootbeer_RootBeerNative_setLogDebugMessages__Z)
       at com.scottyab.rootbeer.RootBeerNative.setLogDebugMessages(Unknown Source)
       at com.scottyab.rootbeer.RootBeer.checkForRootNative(Unknown Source)
       at com.scottyab.rootbeer.RootBeer.isRootedWithoutBusyBoxCheck(Unknown Source)

**Comment by soenkegissel** [comment]
Me too. 
This is my google developer console report.:
![image](https://user-images.githubusercontent.com/13346316/41406258-30b5865e-6fcc-11e8-8d60-9f263070cfed.png)
But in the source of RootBeer.java it says:

public boolean checkForRootNative() {
[...]
        RootBeerNative rootBeerNative = new RootBeerNative();
        try {
            rootBeerNative.setLogDebugMessages(loggingEnabled);
            return rootBeerNative.checkForRoot(paths) > 0;
        } **catch (UnsatisfiedLinkError e)** {
            return false;
        }
 }
So is my app crashing or is this Exception caught and returning false so the app can continue running?
Kindest

**Comment by stealthcopter** [comment]
I've changed the way the build works in the latest (0.0.7) release so that if the NDK is not found, it will use the bundled .so files otherwise it will compile them. Please let me know if this fixes the issues you were having. Thanks

**Comment by soenkegissel** [comment]
Some users actually have an issue with the bundles .so files which raise a UnsatisfiedLinkError.
But this issue is raised bacause there is no implementation found of the RootBeerNative setLogDebugMessages function.
Look at some of the forks of this project and you will see that some branches are even named after this problem.
Kindest

**Comment by stealthcopter** [comment]
I believe that was caused by outdated .so files being bundled with the app accidentally (probably my fault, Sorry!). The method def exists in the C code and in the .so files provided now. This is now fixed in the latest version, and even so if the NDK is found while using this library it will compile the .so files and use those versions rather than the bundled ones. So double fixed :)

**Comment by mahditajdini** [comment]
> I believe that was caused by outdated .so files being bundled with the app accidentally (probably my fault, Sorry!). The method def exists in the C code and in the .so files provided now. This is now fixed in the latest version, and even so if the NDK is found while using this library it will compile the .so files and use those versions rather than the bundled ones. So double fixed :)

I am using version 0.1.0 and this problem is still being reported by my users
